### ISSUE TITLE
Upstream issue tracking

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/as3-crypto#13]
The original repo can be found on [Google Code](https://code.google.com/p/as3crypto).

List of issues:
- [x] <del>[#1](https://code.google.com/p/as3crypto/issues/detail?id=1) Inline ASDoc comments not allowed</del>  
  Addressed by 34d0618ef62138c8cebacd5bbc0365958a083d70
- [ ] [#2](https://code.google.com/p/as3crypto/issues/detail?id=2) TLSEngine reports errors when connecting over VPN vs. straight LAN.
- [ ] [#3](https://code.google.com/p/as3crypto/issues/detail?id=3) Common Name mismatches cause immediate errors, with no exit/ignore strategy.
- [ ] [#4](https://code.google.com/p/as3crypto/issues/detail?id=4) TLSSocket doesn't send handshake
- [ ] [#5](https://code.google.com/p/as3crypto/issues/detail?id=5) Wildcards not supported in tls
- [ ] [#6](https://code.google.com/p/as3crypto/issues/detail?id=6) Cannot get TLS to work from server
- [ ] [#7](https://code.google.com/p/as3crypto/issues/detail?id=7) RSA Verify fails due to TypeError: Error #2007: Parameter bytes must be non-null. 
- [ ] [#8](https://code.google.com/p/as3crypto/issues/detail?id=8) Error with plus.pop.mail.yahoo.com
- [x] <del>[#10](https://code.google.com/p/as3crypto/issues/detail?id=10) build fails for flex sdk 3.2</del>  
  Resolution: build-swc.xml is no longer used
- [ ] [#11](https://code.google.com/p/as3crypto/issues/detail?id=11) AFAIK nothing on the Secret Key page actually works on the demo
- [ ] [#12](https://code.google.com/p/as3crypto/issues/detail?id=12) Does it support reading keys from a keystore?
- [ ] [#13](https://code.google.com/p/as3crypto/issues/detail?id=13) X509Certificate.isSigned does not seem to respect timezones
- [ ] [#14](https://code.google.com/p/as3crypto/issues/detail?id=14) TLSEngine produces incorrect packets for data longer than 16KB.
- [x] <del>[#15](https://code.google.com/p/as3crypto/issues/detail?id=15) Crypto adds too much to a project's filesize.</del>  
  Tests are [no longer included in the build](https://github.com/timkurvers/as3-crypto/commit/f5fecb07b6df0e8c60c4c0a8b71c6eeffbb59060) and as [outlined](https://github.com/timkurvers/as3-crypto/blob/master/src/com/hurlant/crypto/Crypto.as#L45) one does not necessarily need to use the convenience class.
- [ ] [#16](https://code.google.com/p/as3crypto/issues/detail?id=16) Support for diffie-hellman algorithm
- [ ] [#17](https://code.google.com/p/as3crypto/issues/detail?id=17) RSA encryption causes BadPaddingException on Java decryption
- [ ] [#18](https://code.google.com/p/as3crypto/issues/detail?id=18) RSA ecrypt Error when decrypt large amount of  data
- [ ] [#19](https://code.google.com/p/as3crypto/issues/detail?id=19) extra return in TLSSocket
- [x] <del>[#20](https://code.google.com/p/as3crypto/issues/detail?id=20) Allow ASDOCs to be build</del>  
  Addressed by 34d0618ef62138c8cebacd5bbc0365958a083d70
- [ ] [#21](https://code.google.com/p/as3crypto/issues/detail?id=21) TripleDES implementation is not compatable with .NET's
- [x] <del>[#22](https://code.google.com/p/as3crypto/issues/detail?id=22) flex2.compiler.as3.SignatureExtension.SignatureGenerationFailed when compiling com.hurlant.crypto.symmetric.AESKey</del>  
  Flex compiler bug from the past
- [ ] [#23](https://code.google.com/p/as3crypto/issues/detail?id=23) Self-signed cert fails on connect
- [x] <del>[#24](https://code.google.com/p/as3crypto/issues/detail?id=24) Mozilla Certificates tool.</del>  
  Addressed by 19767fc6768af822802cb4eb49142e9cec43511c
- [ ] [#25](https://code.google.com/p/as3crypto/issues/detail?id=25) TLSSocket "pure virtual function call"
- [ ] [#26](https://code.google.com/p/as3crypto/issues/detail?id=26) RSAKey verify error (PKCS#1 unpad: i=0, expected b[i]==[0,1,2])
- [ ] [#27](https://code.google.com/p/as3crypto/issues/detail?id=27) Inconsistent behavior on 64-bit flash runtime in Linux
- [ ] [#28](https://code.google.com/p/as3crypto/issues/detail?id=28) bug in decrypting
- [ ] [#29](https://code.google.com/p/as3crypto/issues/detail?id=29) Encrypt function works periodically
- [ ] [#30](https://code.google.com/p/as3crypto/issues/detail?id=30) AES mode Error
- [ ] [#31](https://code.google.com/p/as3crypto/issues/detail?id=31) Lot of run-time errors in http://crypto.hurlant.com/demo/
- [ ] [#32](https://code.google.com/p/as3crypto/issues/detail?id=32) readRSAPublicKey fails to load key with arr[1].position = 1;
- [ ] [#33](https://code.google.com/p/as3crypto/issues/detail?id=33) protected var h:Array  on SHA256 
- [ ] [#34](https://code.google.com/p/as3crypto/issues/detail?id=34) toString(10) in a BigInteger enters an infinite loop
- [ ] [#35](https://code.google.com/p/as3crypto/issues/detail?id=35) TLS socket Cross-domain Problem
- [x] <del>[#36](https://code.google.com/p/as3crypto/issues/detail?id=36) include 700% faster base64 class</del>  
  See #1, addressed by a1e287bf3fe74d7677c0ff614263d5c1d8eece33
- [ ] [#37](https://code.google.com/p/as3crypto/issues/detail?id=37) Base64
- [ ] [#39](https://code.google.com/p/as3crypto/issues/detail?id=39) I DONT KNOW HOW TO HANDLE DER stuff of TYPE 22
- [ ] [#40](https://code.google.com/p/as3crypto/issues/detail?id=40) Encryption error
- [ ] [#41](https://code.google.com/p/as3crypto/issues/detail?id=41) What about async encryption process impl?
- [ ] [#42](https://code.google.com/p/as3crypto/issues/detail?id=42) Decrypting Text-based Blowfish Encryption in CBC Mode
- [ ] [#43](https://code.google.com/p/as3crypto/issues/detail?id=43) XTea implementation is wrong
- [ ] [#44](https://code.google.com/p/as3crypto/issues/detail?id=44) Java encrypted content fails to decrypt with Private Key
- [ ] [#45](https://code.google.com/p/as3crypto/issues/detail?id=45) Compiler error in AESKey: for-loops in static initializers should be nested inside anonymous functions
- [ ] [#46](https://code.google.com/p/as3crypto/issues/detail?id=46) Automatic initialization vector in IVMode class fails.
- [ ] [#47](https://code.google.com/p/as3crypto/issues/detail?id=47) RSA decrypt skips the first byte of data
- [ ] [#48](https://code.google.com/p/as3crypto/issues/detail?id=48) AESKey.decrypt only decrypts the first 16 bytes of a message correctly, and put the rest of the encrtyped message on the end.
- [ ] [#49](https://code.google.com/p/as3crypto/issues/detail?id=49) IHash#hash should take an IDataInput rather than ByteArray
- [ ] [#50](https://code.google.com/p/as3crypto/issues/detail?id=50) RSA sign fail on xmlsec verify.
- [ ] [#51](https://code.google.com/p/as3crypto/issues/detail?id=51) AES encryption is incompatible with java AES decryption - always gives BadPaddingException
- [ ] [#52](https://code.google.com/p/as3crypto/issues/detail?id=52) RSAKey canDecrypt and canEncrypt flags not set in RSAKey.generate() method
- [ ] [#53](https://code.google.com/p/as3crypto/issues/detail?id=53) Hex.toString()/fromString is not 100% reversible
- [ ] [#54](https://code.google.com/p/as3crypto/issues/detail?id=54) Submitted Patch for various certificate parsing issues
- [ ] [#55](https://code.google.com/p/as3crypto/issues/detail?id=55) Found typo!
- [ ] [#56](https://code.google.com/p/as3crypto/issues/detail?id=56) Strange code in BigInteger
- [ ] [#57](https://code.google.com/p/as3crypto/issues/detail?id=57) rsa problem
- [ ] [#58](https://code.google.com/p/as3crypto/issues/detail?id=58) Found typo! in RSA Verify
- [ ] [#59](https://code.google.com/p/as3crypto/issues/detail?id=59) Found error! in RSA _encrypt ( r28 )
- [x] <del>[#60](https://code.google.com/p/as3crypto/issues/detail?id=60) Base64 decode is incorrect when working with double-byte characters</del>  
  Covered with test-case in 8d9aa48c5a2fb63d688a30914239fcdc91e40c97
- [x] <del>[#61](https://code.google.com/p/as3crypto/issues/detail?id=61) Constructor of BigInteger doesn't support negative numbers</del>  
  Addressed by 35dad947339183276080e095c211f9c2463d267d
- [ ] [#62](https://code.google.com/p/as3crypto/issues/detail?id=62) CTRMode broken - pads final block even with NullPad
- [ ] [#63](https://code.google.com/p/as3crypto/issues/detail?id=63) RSA sign function problem
- [ ] [#64](https://code.google.com/p/as3crypto/issues/detail?id=64) PKCS#1 unpad: i=0, expected b[i]==2, got b[i]=3b Error: Decrypt error - padding function returned null!
- [ ] [#65](https://code.google.com/p/as3crypto/issues/detail?id=65) encrypt in flash / decrypt in java use RSA
- [ ] [#66](https://code.google.com/p/as3crypto/issues/detail?id=66) Only 64 bits of IV (initialization vector) are used with CBC
- [ ] [#67](https://code.google.com/p/as3crypto/issues/detail?id=67) PKCS 1.5 PADDING
- [ ] [#68](https://code.google.com/p/as3crypto/issues/detail?id=68) Difference between demo outputs and local test outputs
- [ ] [#69](https://code.google.com/p/as3crypto/issues/detail?id=69) Incorrect RC4 generation
- [x] <del>[#70](https://code.google.com/p/as3crypto/issues/detail?id=70) Memory leak in Base64 encode</del>  
  Addressed by a1e287bf3fe74d7677c0ff614263d5c1d8eece33
- [ ] [#71](https://code.google.com/p/as3crypto/issues/detail?id=71) TLSEngine overflow patch has critical errors
- [ ] [#72](https://code.google.com/p/as3crypto/issues/detail?id=72) pkcs1pad crashes in flex application compiled for iOS
- [ ] [#73](https://code.google.com/p/as3crypto/issues/detail?id=73) new BigInteger("0", 10) is not equal to BigInteger.nbv(0)
- [ ] [#74](https://code.google.com/p/as3crypto/issues/detail?id=74) Patch for /trunk/as3crypto/src/com/hurlant/crypto/hash/SHABase.as
- [ ] [#75](https://code.google.com/p/as3crypto/issues/detail?id=75) Patch for /trunk/as3crypto/src/com/hurlant/util/asn1/parser/pkcs9unstructuredString.as
